import React from 'react'

export const ActionTypes = {
    SET_PRODUCTS: 'SET_PRODUCTS',
    SELECTED_PRODUCT: 'SELECTED_PRODUCT',
    REMOVE_SELECTED_PRODUCT: 'REMOVE_SELECTED_PRODUCT',
    ADD_TO_CART: 'ADD_TO_CART',
    REMOVE_FROM_CART: 'REMOVE_FROM_CART',
    SET_CART_ITEMS: 'SET_CART_ITEMS',
    SET_CART_TOTAL: 'SET_CART_TOTAL',
    SET_CART_ITEMS_COUNT: 'SET_CART_ITEMS_COUNT',
    SET_CART_ITEMS_COUNT_IN_CART: 'SET_CART_ITEMS_COUNT_IN_CART',
    SET_CART_ITEMS_COUNT_IN_CART_INCREMENT: 'SET_CART_ITEMS_COUNT_IN_CART_INCREMENT',
    SET_CART_ITEMS_COUNT_IN_CART_DECREMENT: 'SET_CART_ITEMS_COUNT_IN_CART_DECREMENT',
    SET_CART_ITEMS_COUNT_IN_CART_RESET: 'SET_CART_ITEMS_COUNT_IN_CART_RESET',
    SET_CART_ITEMS_COUNT_IN_CART_RESET_ALL: 'SET_CART_ITEMS_COUNT_IN_CART_RESET_ALL',
    
}
